module LBFGS_doc_mod

  use sep
  
  implicit none

contains

  subroutine LBFGS_doc()
    call sep_add_doc_line("NAME")
    call sep_add_doc_line("")
    call sep_add_doc_line("    L_BFGS.x - Limited Memory BFGS ")
    call sep_add_doc_line("")
    call sep_add_doc_line("SYNOPSIS")
    call sep_add_doc_line("")
    call sep_add_doc_line("    L_BFGS.x Model=mod.H Gradient=grad.H Function=fct.H Initial_Model=initmod.H Gradient_Weight=gw.H step_init= xmin= xmax= lbfgs_type= bound_type= stp1_opt= > /dev/null ")
    call sep_add_doc_line("")
    call sep_add_doc_line("INPUT FILES")
    call sep_add_doc_line("")
    call sep_add_doc_line("    Model         - Model space vector at current iteration (X)")
    call sep_add_doc_line("    Gradient      - Gradient vector at current iteration G(X)")
    call sep_add_doc_line("    Function      - Value of objective function at current iteration F(X)")
    call sep_add_doc_line("    Initial_Model - (only if lbfgs_type=1 below) Model space vector for starting model (X0)")
    call sep_add_doc_line("")
    call sep_add_doc_line("OPTIONAL INPUT FILES")
    call sep_add_doc_line("")
    call sep_add_doc_line("    Gradient_Weight - Masking function (not weight) applied to the gradient (mask for instance) W(X)")
    call sep_add_doc_line("                      This masking function is set to either 0 or 1 indicating regions where X doesn't change.")
    call sep_add_doc_line("                      The mask is used if and only if lbfgs_type=1 below.")
    call sep_add_doc_line("")
    call sep_add_doc_line("INPUT PARAMETERS")
    call sep_add_doc_line("")
    call sep_add_doc_line("    lbfgs_type - integer: BFGS option")
    call sep_add_doc_line("               0 (default): original LBFGS solver without clipping or masking applied (good for LSRTM for instance)")
    call sep_add_doc_line("               1          : modified LBFGS solver with clipping or masking applied (good for FWI)")
    call sep_add_doc_line("")
    call sep_add_doc_line("    stp1_opt - integer: Line search option (activated if lbfgs_type=1)")
    call sep_add_doc_line("               0 (default): alpha=1/(grad(m)'.grad(m)). This is also the default for lbfgs_type=0")
    call sep_add_doc_line("               1          : alpha=x'x/g'g/100, roughly 1% of velocity change (good for FWI)")
    call sep_add_doc_line("")
    call sep_add_doc_line("OPTIONAL INPUT PARAMETERS")
    call sep_add_doc_line("")
    call sep_add_doc_line("    step_init - float")
    call sep_add_doc_line("              Initial value of the steplength alpha for x+1=x+alpha*g(x). One way to set step_init up is to run the inversion for a small")
    call sep_add_doc_line("              subset of the data without step_init. In that case and if we are not doing FWI, the initial value becomes alpha=1/(grad(m)'.grad(m)).")
    call sep_add_doc_line("              and it might take many iterations to find the first good alpha (but fast since we use a small subset).")
    call sep_add_doc_line("              For FWI, and if stp1_opt=1 step_init is not often needed and the default initial value of the steplength ensures that the gradient")
    call sep_add_doc_line("              promotes a 1% increase in the velocity model (alpha=x'x/g'g/100)")
    call sep_add_doc_line("              If we can have a good initial value step_init, it is a better option to use it.")
    call sep_add_doc_line("")
    call sep_add_doc_line("OPTIONAL INPUT FILE")

    call sep_add_doc_line("")
    call sep_add_doc_line("OUTPUT PARAMETERS")

    call sep_add_doc_line("")
    call sep_add_doc_line("DESCRIPTION")
    call sep_add_doc_line("")
    call sep_add_doc_line("      LIMITED MEMORY BFGS METHOD FOR LARGE SCALE OPTIMIZATION          ")
    call sep_add_doc_line("                         JORGE NOCEDAL                                 ")
    call sep_add_doc_line("                       *** July 1990 ***")
    call sep_add_doc_line("")
    call sep_add_doc_line("")
    call sep_add_doc_line("       This program solves the unconstrained minimization problem      ")
    call sep_add_doc_line("")
    call sep_add_doc_line("")
    call sep_add_doc_line("                     min F(x),    x= (x1,x2,...,xN),                   ")
    call sep_add_doc_line("")
    call sep_add_doc_line("     using the limited memory BFGS method. The routine is especially   ")
    call sep_add_doc_line("     effective on problems involving a large number of variables. In a ")
    call sep_add_doc_line("     typical iteration of this method an approximation Hk to the       ")
    call sep_add_doc_line("     inverse of the Hessian is obtained by applying M BFGS updates to a")
    call sep_add_doc_line("     diagonal matrix Hk0, using information from the previous M steps. ")
    call sep_add_doc_line("     The user specifies the number M, which determines the amount of   ")
    call sep_add_doc_line("     storage required by the routine.                                  ")
    call sep_add_doc_line("     The algorithm is described in ""On the limited memory BFGS method ")
    call sep_add_doc_line("     for large scale optimization"", by D. Liu and J. Nocedal,         ")
    call sep_add_doc_line("     Mathematical Programming B 45 (1989) 503-528.                     ")
    call sep_add_doc_line("")
    call sep_add_doc_line("     The user is required to calculate the function value F and its    ")
    call sep_add_doc_line("     gradient G. In order to allow the user complete control over      ")
    call sep_add_doc_line("     these computations, reverse  communication is used. The routine   ")
    call sep_add_doc_line("     must be called repeatedly under the control of the parameter      ")
    call sep_add_doc_line("     IFLAG read from file Iflag.dat ")

    call sep_add_doc_line("     The steplength is determined at each iteration by means of the    ")
    call sep_add_doc_line("     line search routine MCSRCH, which is a slight modification of     ")
    call sep_add_doc_line("     the routine CSRCH written by More' and Thuente.                   ")
    call sep_add_doc_line("")
    call sep_add_doc_line("COMMENTS")
    call sep_add_doc_line("")
    call sep_add_doc_line("      L_BFGS.x computes a model update only once and reads/saves its computational status ")
    call sep_add_doc_line("      in .dat files: Diag[Out].dat, Iflag[Out].dat, Info[Out].dat, LbfgsDat[Out].dat      ")
    call sep_add_doc_line("      McsrchDat[Out].dat,and WorkArray[out].dat ")
    call sep_add_doc_line("      These files don't need to exist before the inversion starts.")
    call sep_add_doc_line("      In practice, L_BFGS.x is called within a do loop where the objective function and gradient are")
    call sep_add_doc_line("      computed as well.")
    call doc('SOURCE')

  end subroutine LBFGS_DOC

end module LBFGS_doc_mod
