include ${SEPINC}/SEP.top
include ../../makefile

default: ${BINDIR}/DdotOC.x ${BINDIR}/Ddot_gg_rr_ss_OC.x ${BINDIR}/Compute_alfa_beta.x ${BINDIR}/Update_cg_vectors.x ${BINDIR}/Add_long.x ${BINDIR}/L_BFGS.x ${BINDIR}/Compute_Norm.x ${BINDIR}/Blockymodel.x

aclean: jclean       
	@-${RM} ${BINDIR}/*.x

include ${SEPINC}/SEP.bottom
