include ${SEPINC}/SEP.top
include ../../makefile

default: ${BINDIR}/3DBORNMOD.x ${BINDIR}/Acoustic_modeling_sep.x #${BINDIR}/Acoustic_Born_modeling.x ${BINDIR}/Acoustic_modeling_sep.x ${BINDIR}/Acoustic_Born_modeling_opt.x ${BINDIR}/Acoustic_Born_modeling_opt_memory.x

aclean: jclean       
	@-${RM} ${BINDIR}/*.x 

include ${SEPINC}/SEP.bottom
