include ${SEPINC}/SEP.top
include ../../makefile

default: ${BINDIR}/Acoustic_modeling_sep.x ${BINDIR}/Acoustic_Born_modeling_sep.x 

aclean: jclean       
	@-${RM} ${BINDIR}/*.x 

include ${SEPINC}/SEP.bottom
