module Common_Doc

  use sep

  implicit none

contains

  subroutine Com_doc()
    call sep_add_doc_line("    stdin - sepfile")
    call sep_add_doc_line("               wavelet.H (nt) = wavelet")
    call sep_add_doc_line("")
    call sep_add_doc_line("    vel - sepfile")
    call sep_add_doc_line("               vel.H (nz,nx,ny) = velocity file")
    call sep_add_doc_line("")
    call sep_add_doc_line("    traces - sepfile")
    call sep_add_doc_line("               traces.H (nt,ntraces) = seismic traces to be migrated")
    call sep_add_doc_line("")
    call sep_add_doc_line("    coordfile - sepfile")
    call sep_add_doc_line("               coord.H (nheaders,ntraces) = header file with coordinates")
    call sep_add_doc_line("")
    call sep_add_doc_line("    keysx - integer")
    call sep_add_doc_line("                Shot X key index in coord.H file")
    call sep_add_doc_line("")
    call sep_add_doc_line("    keysy - integer")
    call sep_add_doc_line("                Shot Y key index in coord.H file")
    call sep_add_doc_line("")
    call sep_add_doc_line("    keyselev - integer")
    call sep_add_doc_line("                Shot Z elevation key index in coord.H file")
    call sep_add_doc_line("")
    call sep_add_doc_line("    keygx - integer")
    call sep_add_doc_line("                Receiver X key index in coord.H file")
    call sep_add_doc_line("")
    call sep_add_doc_line("    keygy - integer")
    call sep_add_doc_line("                Receiver Y key index in coord.H file")
    call sep_add_doc_line("")
    call sep_add_doc_line("    keygelev - integer")
    call sep_add_doc_line("                Receiver Z elevation key index in coord.H file")
    call sep_add_doc_line("")
    call sep_add_doc_line("    aperture_x -real")
    call sep_add_doc_line("               [.] Migration aperture in X")
    call sep_add_doc_line("")
    call sep_add_doc_line("    aperture_y -real")
    call sep_add_doc_line("               [.] Migration aperture in Y")
    call sep_add_doc_line("")
    call sep_add_doc_line("    fmax -real")
    call sep_add_doc_line("               [30.] Maximum frequency in Hz")
    call sep_add_doc_line("")
    call sep_add_doc_line("    num_threads -integer")
    call sep_add_doc_line("               [4] Number of threads for openmp")
    call sep_add_doc_line("")
    call sep_add_doc_line("    snapi -integer")
    call sep_add_doc_line("               [4] Subsampling of wavefields in time to save in memory/disk")
    call sep_add_doc_line("")
    call sep_add_doc_line("    ntaper -integer")
    call sep_add_doc_line("               [10] Size of absorbing boundaries in samples")
    call sep_add_doc_line("")
    call sep_add_doc_line("    lsinc -integer")
    call sep_add_doc_line("               [7] Size of sinc interpolator in samples")
    call sep_add_doc_line("")
    call sep_add_doc_line("    twoD -boolean")
    call sep_add_doc_line("               [0] Whether or not RTM is 2D")
    call sep_add_doc_line("")
    call sep_add_doc_line("    maxsize -real")
    call sep_add_doc_line("               [16.] Maximum memory available on node (Gb), go to disk if not available")
    call sep_add_doc_line("")
    call sep_add_doc_line("    withRho -boolean")
    call sep_add_doc_line("               [0] Without or with density (0,1)")
    call sep_add_doc_line("")
    call sep_add_doc_line("    rec_type -boolean")
    call sep_add_doc_line("               [0] Without or with receiver ghost")
    call sep_add_doc_line("")
    call sep_add_doc_line("    shot_type -boolean")
    call sep_add_doc_line("               [0] Without or with source ghost")
    call sep_add_doc_line("")
    call sep_add_doc_line("    surf_type -boolean")
    call sep_add_doc_line("               [0] Without or with free surface")

  end subroutine Com_doc

end module Common_Doc
