include ${SEPINC}/SEP.top
include ../../makefile


default: ${BINDIR}/MakeHeader.x ${BINDIR}/Change.x ${BINDIR}/Mute3D.x ${BINDIR}/Static.x ${BINDIR}/TaperEdges.x ${BINDIR}/Create_v_of_z_from_water_bottom.x

aclean: jclean       
	@-${RM} ${BINDIR}/*.x

include ${SEPINC}/SEP.bottom
