include ${SEPINC}/SEP.top
include ../../makefile

#default: ${BINDIR}/Acoustic_RTM_sep.x ${BINDIR}/Acoustic_RTM.x

default: ${BINDIR}/Acoustic_RTM_sep.x ${BINDIR}/Acoustic_RTM_opt.x ${BINDIR}/Acoustic_RTM_opt_memory.x

aclean: jclean       
	@-${RM} ${BINDIR}/*.x 

include ${SEPINC}/SEP.bottom
