include ${SEPINC}/SEP.top
include ../../makefile

default: ${BINDIR}/Futprocs.x \
	${BINDIR}/Pick_and_shift.x \
	${BINDIR}/QcompZO_Iterative_inversion.x

aclean: jclean       
	@-${RM} ${BINDIR}/*.x *.o

include ${SEPINC}/SEP.bottom