include ${SEPINC}/SEP.top
include ../../makefile

default: ${BINDIR}/Matching.x ${BINDIR}/Apply_Filter.x ${BINDIR}/Wavelet_Estimation.x

aclean: jclean       
	@-${RM} ${BINDIR}/*.x

include ${SEPINC}/SEP.bottom
